#!/usr/bin/env bash

set -o allexport 
source .env set
set +o allexport

echo "Start $POSTGRES_HOST docker container:"
docker compose up -d $PG_HOST

sleep 2

echo "Apply migration to $POSTGRES_HOST container..."

docker exec $POSTGRES_HOST /bin/sh ./execute_sql_migration.sh

echo "Finished migration"

sleep 1

echo "Start $REDIS_HOST docker container:"
docker compose up -d $REDIS_HOST

sleep 1

echo "Start backend service"

# docker compose up -d rembackend --build

# echo "Start frontend service"
# docker compose up -d frontend --build 
# echo "Database backend and frontend successfully started"
echo "Please go into the frontend folder ( cd frontend ) and execute npm run dev"
